-- ============================================================
-- Bendansalet Marketplace Schema Migration
-- Run against the TrustLink Supabase project
-- ============================================================

-- ── 1. Extend profiles with vendor fields ────────────────────
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS is_vendor BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS vendor_category TEXT CHECK (vendor_category IN ('digital', 'physical', 'services')),
  ADD COLUMN IF NOT EXISTS vendor_subcategory TEXT,
  ADD COLUMN IF NOT EXISTS business_name TEXT,
  ADD COLUMN IF NOT EXISTS business_kyc_status TEXT DEFAULT 'unverified'
    CHECK (business_kyc_status IN ('unverified', 'pending', 'verified')),
  ADD COLUMN IF NOT EXISTS location_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS location_lng NUMERIC,
  ADD COLUMN IF NOT EXISTS location_type TEXT DEFAULT 'fixed'
    CHECK (location_type IN ('fixed', 'mobile')),
  ADD COLUMN IF NOT EXISTS nin_verified BOOLEAN DEFAULT FALSE;

-- ── 2. Create marketplace_requests table ─────────────────────
CREATE TABLE IF NOT EXISTS marketplace_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_wallet_address TEXT NOT NULL,
  seller_wallet_address TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('digital', 'physical', 'services')),
  subcategory TEXT,
  description TEXT,
  proposed_amount NUMERIC NOT NULL,
  counter_amount NUMERIC,
  status TEXT DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'countered', 'rejected', 'expired')),
  converted_escrow_order_id BIGINT REFERENCES escrow_orders(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. Create ratings table ──────────────────────────────────
CREATE TABLE IF NOT EXISTS ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  rater_wallet_address TEXT NOT NULL,
  rated_wallet_address TEXT NOT NULL,
  stars INT NOT NULL CHECK (stars >= 1 AND stars <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(order_id, rater_wallet_address)
);

-- ── 4. Add request_id to messages for pre-escrow chat ────────
ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS request_id BIGINT;

-- ── 5. Atomic accept_request_and_create_order RPC ────────────
-- Prevents orphaned accepted-but-no-order states by doing both
-- in a single transaction (same pattern as release_escrow_and_update_reputation)
CREATE OR REPLACE FUNCTION accept_request_and_create_order(
  p_request_id BIGINT,
  p_seller_wallet TEXT,
  p_buyer_wallet TEXT,
  p_amount NUMERIC,
  p_category TEXT,
  p_subcategory TEXT DEFAULT NULL
)
RETURNS BIGINT AS $$
DECLARE
  v_order_id BIGINT;
  v_request_status TEXT;
BEGIN
  -- Lock the request row to prevent race conditions
  SELECT status INTO v_request_status
  FROM marketplace_requests
  WHERE id = p_request_id
    AND seller_wallet_address = LOWER(p_seller_wallet)
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Request not found or not assigned to this seller';
  END IF;

  IF v_request_status NOT IN ('pending', 'countered') THEN
    RAISE EXCEPTION 'Request is not in an acceptable state (current: %)', v_request_status;
  END IF;

  -- Create escrow order
  INSERT INTO escrow_orders (
    buyer_wallet_address,
    seller_address,
    amount,
    trade_type,
    status,
    description
  ) VALUES (
    p_buyer_wallet,
    p_seller_wallet,
    p_amount,
    'MARKETPLACE_ORDER',
    'secured',
    p_category || COALESCE(' / ' || p_subcategory, '')
  )
  RETURNING id INTO v_order_id;

  -- Update request atomically
  UPDATE marketplace_requests
  SET status = 'accepted',
      converted_escrow_order_id = v_order_id,
      updated_at = NOW()
  WHERE id = p_request_id;

  RETURN v_order_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── 6. RLS Policies ──────────────────────────────────────────

-- marketplace_requests: users can see their own requests
ALTER TABLE marketplace_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own requests" ON marketplace_requests
  FOR SELECT USING (
    LOWER(buyer_wallet_address) = LOWER(auth.jwt() ->> 'wallet_address')
    OR LOWER(seller_wallet_address) = LOWER(auth.jwt() ->> 'wallet_address')
  );

CREATE POLICY "Users can insert own requests" ON marketplace_requests
  FOR INSERT WITH CHECK (
    LOWER(buyer_wallet_address) = LOWER(auth.jwt() ->> 'wallet_address')
  );

-- ratings: users can see all ratings (public trust data), insert own
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view ratings" ON ratings
  FOR SELECT USING (true);

CREATE POLICY "Users can insert own ratings" ON ratings
  FOR INSERT WITH CHECK (
    LOWER(rater_wallet_address) = LOWER(auth.jwt() ->> 'wallet_address')
  );

-- ── 7. Indexes for vendor search performance ─────────────────
CREATE INDEX IF NOT EXISTS idx_profiles_vendor_category
  ON profiles (vendor_category) WHERE is_vendor = TRUE;

CREATE INDEX IF NOT EXISTS idx_profiles_is_vendor
  ON profiles (is_vendor) WHERE is_vendor = TRUE;

CREATE INDEX IF NOT EXISTS idx_marketplace_requests_buyer
  ON marketplace_requests (buyer_wallet_address);

CREATE INDEX IF NOT EXISTS idx_marketplace_requests_seller
  ON marketplace_requests (seller_wallet_address);

CREATE INDEX IF NOT EXISTS idx_ratings_rated
  ON ratings (rated_wallet_address);
