-- Migration: Market Rates Cache Table
-- Used as a tertiary last-known-good cache in the multi-provider waterfall

CREATE TABLE IF NOT EXISTS market_rates_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rates JSONB NOT NULL,
  source TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_market_rates_cache_updated_at ON market_rates_cache (updated_at DESC);
