import { useEffect, useState, useRef } from 'react';
import { usePrivy } from '@privy-io/react-auth';
import { Send, X, Lock, Loader2, AlertCircle } from 'lucide-react';
import { supabase } from '../lib/supabaseClient';

// NOTE: You need to create a 'messages' table in Supabase for this to work perfectly.
// SQL: create table messages (id bigint generated by default as identity primary key, order_id bigint, sender_address text, content text, created_at timestamptz default now());

export default function SecureChat({ peerAddress, orderId, isOpen, onClose }: { peerAddress: string, orderId?: number, isOpen: boolean, onClose: () => void }) {
  const { user } = usePrivy();
  const address = user?.wallet?.address;
  
  const [messages, setMessages] = useState<any[]>([]);
  const [inputText, setInputText] = useState("");
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  // 1. Load & Subscribe to Messages
  useEffect(() => {
    if (!isOpen || !orderId) return;

    const fetchMessages = async () => {
      setLoading(true);
      const { data } = await supabase
        .from('messages')
        .select('*')
        .eq('order_id', orderId)
        .order('created_at', { ascending: true });
      
      if (data) setMessages(data);
      setLoading(false);
    };

    fetchMessages();

    // Realtime Subscription
    const channel = supabase
      .channel(`order-${orderId}`)
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `order_id=eq.${orderId}` }, (payload) => {
          setMessages((prev) => [...prev, payload.new]);
      })
      .subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [isOpen, orderId]);

  // Scroll to bottom
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading, isOpen]);

  // 2. Send Message
  const sendMessage = async () => {
    if (!inputText.trim() || !address || !orderId) return;
    
    const content = inputText;
    setInputText(""); // Optimistic clear

    const { error } = await supabase.from('messages').insert({
        order_id: orderId,
        sender_address: address,
        content: content
    });

    if (error) {
        alert("Failed to send: " + error.message);
        setInputText(content); // Restore text on error
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed bottom-4 right-4 w-80 h-96 bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl flex flex-col overflow-hidden z-50 font-sans">
      
      {/* Header */}
      <div className="bg-slate-950 p-3 flex justify-between items-center border-b border-slate-800">
        <div className="flex items-center gap-2">
            <Lock className="w-3 h-3 text-emerald-400" />
            <span className="text-white font-bold text-xs">Secure Dispute Chat #{orderId}</span>
        </div>
        <button onClick={onClose}><X className="w-4 h-4 text-slate-400 hover:text-white" /></button>
      </div>

      {/* Messages Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-3 bg-slate-900">
        {loading ? (
            <div className="flex justify-center mt-10"><Loader2 className="w-6 h-6 animate-spin text-emerald-500" /></div>
        ) : messages.length === 0 ? (
            <div className="text-center text-slate-600 text-xs mt-10">No messages yet.<br/>Start the negotiation.</div>
        ) : (
            messages.map((msg, i) => {
                const isMe = msg.sender_address?.toLowerCase() === address?.toLowerCase();
                return (
                    <div key={i} className={`flex ${isMe ? 'justify-end' : 'justify-start'}`}>
                        <div className={`max-w-[85%] p-2 rounded-xl text-xs leading-relaxed ${isMe ? 'bg-emerald-600 text-white rounded-br-none' : 'bg-slate-800 text-slate-200 rounded-bl-none'}`}>
                            {msg.content}
                        </div>
                    </div>
                );
            })
        )}
        <div ref={bottomRef} />
      </div>

      {/* Input Area */}
      <div className="p-3 bg-slate-950 border-t border-slate-800 flex gap-2">
        <input 
            type="text" 
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
            placeholder="Type a message..."
            className="flex-1 bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-500 transition-colors"
        />
        <button onClick={sendMessage} disabled={!inputText.trim()} className="bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white p-2 rounded-lg">
            <Send className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}